id: kubernetes-pods-api

info:
  name: Kubernetes Pods - API Discovery & Remote Code Execution
  author: ilovebinbash,geeknik,0xtavian
  severity: critical
  description: A Kubernetes Pods API was discovered. When the service port is available, unauthenticated users can execute commands inside the container.
  reference:
    - https://github.com/officialhocc/Kubernetes-Kubelet-RCE
    - https://blog.binaryedge.io/2018/12/06/kubernetes-being-hijacked-worldwide/
  classification:
    cpe: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
  metadata:
    max-request: 2
    vendor: kubernetes
    product: kubernetes
  tags: k8,unauth,kubernetes,devops,misconfig,vuln

http:
  - method: GET
    path:
      - '{{BaseURL}}/pods'
      - '{{BaseURL}}/api/v1/pods'

    matchers-condition: and
    matchers:
      - type: word
        name: kubernetes
        cpe: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
        words:
          - "apiVersion"

      - type: word
        name: kubernetes-2
        cpe: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
        words:
          - "application/json"
        part: header

      - type: status
        status:
          - 200
