id: netlify-phish

info:
  name: Netlify phishing Detection
  author: rxerium
  severity: info
  description: |
    A Netlify phishing website was detected
  reference:
    - https://netlify.com
  classification:
    cpe: cpe:2.3:a:netlify:netlify:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: netlify
    product: netlify
  tags: phishing,netlify,hosting,osint,discovery
http:
  - method: GET
    path:
      - "{{BaseURL}}"

    host-redirects: true
    max-redirects: 2

    matchers-condition: and
    matchers:
      - type: word
        name: netlify
        cpe: cpe:2.3:a:netlify:netlify:*:*:*:*:*:*:*:*
        words:
          - 'Build with AI or code, deploy instantly. One platform with everything you need to make real apps live.'

      - type: status
        status:
          - 200

      - type: dsl
        name: netlify-2
        cpe: cpe:2.3:a:netlify:netlify:*:*:*:*:*:*:*:*
        dsl:
          - '!contains(host,"netlify.com")'
