id: deployment-interface-exposed

info:
  name: Deployment Management Interface - Exposed
  author: DhiyaneshDK
  severity: medium
  description: |
   Deployment Management Interface is exposed. This exposure could potentially allow unauthorized access to the management interface
  classification:
    cpe: cpe:2.3:a:deployment:deployment:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: deployment
    product: deployment
  tags: deployment,management,misconfig,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/"

    matchers-condition: and
    matchers:
      - type: word
        name: deployment
        cpe: cpe:2.3:a:deployment:deployment:*:*:*:*:*:*:*:*
        part: body
        words:
          - "<title>Deployment Management Interface</title>"

      - type: status
        status:
          - 200
