id: 3cx-config

info:
  name: 3CX Config - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    3CX Configuration file was discovered.
  reference:
    - https://www.3cx.com/docs/configure-pbx-automatically/
  classification:
    cpe: cpe:2.3:a:3cx:3cx:*:*:*:*:*:*:*:*
    cwe-id: CWE-219,CWE-552
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"setupconfig.xml"
    vendor: 3cx
    product: 3cx
  tags: 3cx,config,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/SetupConfig.xml"

    matchers-condition: and
    matchers:
      - type: word
        name: 3cx
        cpe: cpe:2.3:a:3cx:3cx:*:*:*:*:*:*:*:*
        part: body
        words:
          - "3CX"
          - "<SetupConfig"
        condition: and

      - type: word
        name: 3cx-2
        cpe: cpe:2.3:a:3cx:3cx:*:*:*:*:*:*:*:*
        part: content_type
        words:
          - "application/xml"
