id: awstats-config

info:
  name: AWStats Config - Detect
  author: sheikhrishad
  severity: info
  description: AWStats configuration information was detected.
  reference:
    - https://www.awstats.org/
  classification:
    cpe: cpe:2.3:a:awstats:awstats:*:*:*:*:*:*:*:*
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 2
    vendor: awstats
    product: awstats
  tags: config,exposure,awstats,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/awstats/"
      - "{{BaseURL}}/awstats.conf"

    matchers:
      - type: word
        name: awstats
        cpe: cpe:2.3:a:awstats:awstats:*:*:*:*:*:*:*:*
        words:
          - "AWSTATS CONFIGURE"
          - "MAIN SETUP SECTION"
        condition: and

      - type: word
        name: awstats-2
        cpe: cpe:2.3:a:awstats:awstats:*:*:*:*:*:*:*:*
        words:
          - "Index of /awstats"
          - "Parent Directory"
        condition: and
