id: bash-config-exposure

info:
  name: Bash Configuration - Exposure
  author: theamanrawat
  severity: low
  description: |
    Detected exposed bash configuration on web servers that could have contained sensitive information such as credentials, API keys, database connection strings, or internal paths.
  classification:
    cpe: cpe:2.3:a:bash:bash:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    vendor: bash
    product: bash
  tags: exposure,config,misconfig,bash

http:
  - method: GET
    path:
      - "{{BaseURL}}/.bashrc"
      - "{{BaseURL}}/.bash_profile"
      - "{{BaseURL}}/.profile"
      - "{{BaseURL}}/.zshrc"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: regex
        name: bash
        cpe: cpe:2.3:a:bash:bash:*:*:*:*:*:*:*:*
        part: body
        regex:
          - "usr/(local|bin)/"

      - type: word
        name: bash-2
        cpe: cpe:2.3:a:bash:bash:*:*:*:*:*:*:*:*
        part: body
        words:
          - "export "
          - "source "
          - "if ["
          - "then"
          - "echo "
          - "for "
          - "do"
          - "done"
        condition: or

      - type: word
        name: bash-3
        cpe: cpe:2.3:a:bash:bash:*:*:*:*:*:*:*:*
        part: body
        words:
          - "<html"
          - "<!DOCTYPE"
          - "404"
          - "Not Found"
        negative: true

      - type: status
        status:
          - 200
