id: codeclimate-config-exposure

info:
  name: CodeClimate Configuration File - Exposure
  author: 0x_Akoko
  severity: info
  description: |
    Detected CodeClimate configuration file, exposing code quality settings and excluded paths.
  reference:
    - https://docs.codeclimate.com/docs/configuring-your-workflow
  classification:
    cpe: cpe:2.3:a:codeclimate:codeclimate:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: codeclimate
    product: codeclimate
  tags: exposure,config,codeclimate

http:
  - method: GET
    path:
      - "{{BaseURL}}/.codeclimate.yml"

    matchers-condition: and
    matchers:
      - type: word
        name: codeclimate
        cpe: cpe:2.3:a:codeclimate:codeclimate:*:*:*:*:*:*:*:*
        part: body
        words:
          - "languages:"
          - "engines:"
          - "exclude_paths:"
        condition: and

      - type: status
        status:
          - 200
