id: detect-drone-config

info:
  name: Drone - Configuration Detection
  author: geeknik
  severity: high
  description: Drone configuration was discovered.
  reference:
    - https://github.com/drone/drone
  classification:
    cpe: cpe:2.3:a:drone:drone:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: drone
    product: drone
  tags: config,exposure,drone,discovery

http:
  - method: GET
    path:
      - "{{BaseURL}}/.drone.yml"

    matchers-condition: and
    matchers:
      - type: word
        name: drone
        cpe: cpe:2.3:a:drone:drone:*:*:*:*:*:*:*:*
        words:
          - "kind:"
          - "name:"
          - "steps:"
        condition: and

      - type: status
        status:
          - 200
