id: dockerfile-hidden-disclosure

info:
  name: Dockerfile - Detect
  author: dhiyaneshDk
  severity: medium
  description: Dockerfile was detected.
  reference:
    - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/dockerfile-hidden-disclosure.json
  classification:
    cpe: cpe:2.3:a:dockerfile-hidden:dockerfile-hidden:*:*:*:*:*:*:*:*
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 3
    vendor: dockerfile-hidden
    product: dockerfile-hidden
  tags: exposure,config,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/.dockerfile"
      - "{{BaseURL}}/.Dockerfile"
      - "{{BaseURL}}/Dockerfile"

    matchers-condition: and
    matchers:
      - type: regex
        name: dockerfile-hidden
        cpe: cpe:2.3:a:dockerfile-hidden:dockerfile-hidden:*:*:*:*:*:*:*:*
        regex:
          - '^(?:FROM(?:CACHE)?|RUN|ADD|WORKDIR|ENV|EXPOSE|\#)\s+[ -~]+'
        part: body

      - type: status
        status:
          - 200

      - type: word
        name: dockerfile-hidden-2
        cpe: cpe:2.3:a:dockerfile-hidden:dockerfile-hidden:*:*:*:*:*:*:*:*
        part: header
        words:
          - "text/html"
        negative: true
