id: exposed-bitkeeper

info:
  name: BitKeeper Configuration - Detect
  author: daffainfo
  severity: low
  description: BitKeeper configuration was detected.
  reference:
    - https://www.bitkeeper.org/man/config-etc.html
  classification:
    cpe: cpe:2.3:a:exposed-bitkeeper:exposed-bitkeeper:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: exposed-bitkeeper
    product: exposed-bitkeeper
  tags: config,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/BitKeeper/etc/config"

    matchers-condition: and
    matchers:
      - type: word
        name: exposed-bitkeeper
        cpe: cpe:2.3:a:exposed-bitkeeper:exposed-bitkeeper:*:*:*:*:*:*:*:*
        words:
          - "BitKeeper configuration"
          - "logging"
          - "email"
          - "description"
        condition: and

      - type: status
        status:
          - 200
