id: msmtp-config

info:
  name: Msmtp - Config Exposure
  author: geeknik
  severity: high
  description: Msmtp configuration was discovered.
  reference:
    - https://wiki.archlinux.org/title/Msmtp
  classification:
    cpe: cpe:2.3:a:msmtp:msmtp:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: msmtp
    product: msmtp
  tags: exposure,msmtp,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/.msmtprc"

    matchers-condition: and
    matchers:
      - type: word
        name: msmtp
        cpe: cpe:2.3:a:msmtp:msmtp:*:*:*:*:*:*:*:*
        words:
          - 'account'
          - 'host'
          - 'from'
          - 'auth'
          - 'tls'
        condition: and

      - type: word
        name: msmtp-2
        cpe: cpe:2.3:a:msmtp:msmtp:*:*:*:*:*:*:*:*
        part: header
        words:
          - 'text/plain'
          - 'octet-stream'
        condition: or

      - type: status
        status:
          - 200
