id: opcache-status-exposure

info:
  name: OPcache Status Page - Detect
  author: pdteam
  severity: medium
  description: OPcache status page was detected.
  reference:
    - https://www.php.net/manual/en/book.opcache.php
  classification:
    cpe: cpe:2.3:a:opcache:opcache:*:*:*:*:*:*:*:*
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 3
    vendor: opcache
    product: opcache
  tags: config,exposure,status,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/opcache-status/"
      - "{{BaseURL}}/php-opcache-status/"
      - "{{BaseURL}}/opcache-status/opcache.php"

    matchers:
      - type: word
        name: opcache
        cpe: cpe:2.3:a:opcache:opcache:*:*:*:*:*:*:*:*
        words:
          - "<th>opcache_enabled</th>"
          - "<th>opcache_hit_rate</th>"
        condition: and
        part: body
