id: phpci-yml

info:
  name: PHPCI Configuration Exposure "phpci.yml" Exposure
  author: DhiyaneshDk
  severity: info
  description: |
    PHPCI Configuration "phpci.yml" File was exposed.
  reference:
    - https://github.com/dancryer/PHPCI/blob/master/.phpci.yml
  classification:
    cpe: cpe:2.3:a:phpci:phpci:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="phpci.yml"
    vendor: phpci
    product: phpci
  tags: phpci,misconfig,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/phpci.yml"
      - "{{BaseURL}}/ci/phpci.yml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        name: phpci
        cpe: cpe:2.3:a:phpci:phpci:*:*:*:*:*:*:*:*
        part: body
        words:
          - 'build_settings:'
          - 'setup:'
          - 'php_unit:'
        condition: and

      - type: word
        name: phpci-2
        cpe: cpe:2.3:a:phpci:phpci:*:*:*:*:*:*:*:*
        part: content_type
        words:
          - 'application/octet-stream'
          - "application/x-yaml"
          - "text/yaml"
          - "text/plain"
        condition: or

      - type: status
        status:
          - 200
