id: protractor-config

info:
  name: Protractor Configuration Exposure
  author: DhiyaneshDK
  severity: low
  description: |
    Protractor configuration file was detected.
  reference:
    - https://www.protractortest.org/#/api-overview
  classification:
    cpe: cpe:2.3:a:protractor:protractor:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"protractor.conf.js"
    vendor: protractor
    product: protractor
  tags: devops,exposure,protractor,config,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/protractor.conf.js"

    matchers-condition: and
    matchers:
      - type: word
        name: protractor
        cpe: cpe:2.3:a:protractor:protractor:*:*:*:*:*:*:*:*
        part: body
        words:
          - 'exports.config'
          - 'capabilities:'
        condition: and

      - type: word
        name: protractor-2
        cpe: cpe:2.3:a:protractor:protractor:*:*:*:*:*:*:*:*
        part: header
        words:
          - "application/javascript"

      - type: status
        status:
          - 200
