id: psalm-config

info:
  name: Psalm Configuration Exposure - Detect
  author: DhiyaneshDK
  severity: low
  description: |
    Psalm configuration page was detected.
  reference:
    - https://psalm.dev/docs/running_psalm/configuration/
  classification:
    cpe: cpe:2.3:a:psalm:psalm:*:*:*:*:*:*:*:*
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"psalm.xml"
    vendor: psalm
    product: psalm
  tags: devops,exposure,php,psalm,config,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/psalm.xml"

    matchers-condition: and
    matchers:
      - type: word
        name: psalm
        cpe: cpe:2.3:a:psalm:psalm:*:*:*:*:*:*:*:*
        part: body
        words:
          - '<psalm'
          - '<projectFiles'
          - 'xmlns:xsi'
        condition: and

      - type: word
        name: psalm-2
        cpe: cpe:2.3:a:psalm:psalm:*:*:*:*:*:*:*:*
        part: header
        words:
          - "application/xml"

      - type: status
        status:
          - 200
