id: rails-database-config

info:
  name: Ruby on Rails Database Configuration File - Detect
  author: pdteam,geeknik
  severity: high
  description: Ruby on Rails database configuration file was detected, which may contain database credentials.
  reference:
    - https://guides.rubyonrails.org/configuring.html#configuring-a-database
  classification:
    cpe: cpe:2.3:a:rails:rails:*:*:*:*:*:*:*:*
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
    vendor: rails
    product: rails
  tags: config,exposure,rails,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/config/database.yml"

    matchers-condition: and
    matchers:
      - type: word
        name: rails
        cpe: cpe:2.3:a:rails:rails:*:*:*:*:*:*:*:*
        words:
          - "adapter:"
          - "database:"
          - "production:"
        condition: and
        part: body

      - type: status
        status:
          - 200
