id: robomongo-credential

info:
  name: RoboMongo Credential - Exposure
  author: geeknik
  severity: high
  description: |
    A MongoDB credentials file used by RoboMongo was detected.
  reference:
    - https://robomongo.org/
  classification:
    cpe: cpe:2.3:a:robomongo:robomongo:*:*:*:*:*:*:*:*
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 2
    vendor: robomongo
    product: robomongo
  tags: mongodb,robomongo,disclosure,config,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/db/robomongo.json"
      - "{{BaseURL}}/robomongo.json"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        name: robomongo
        cpe: cpe:2.3:a:robomongo:robomongo:*:*:*:*:*:*:*:*
        words:
          - "databaseName"
          - "userName"
          - "userPassword"
          - "serverHost"
        condition: and

      - type: word
        name: robomongo-2
        cpe: cpe:2.3:a:robomongo:robomongo:*:*:*:*:*:*:*:*
        part: header
        words:
          - "application/json"

      - type: status
        status:
          - 200
