id: s3cfg-config

info:
  name: S3CFG Configuration - Detect
  author: geeknik,DhiyaneshDK
  severity: high
  description: S3CFG configuration file was detected.
  reference:
    - https://s3tools.org/kb/item14.htm
  classification:
    cpe: cpe:2.3:a:s3cfg-config:s3cfg-config:*:*:*:*:*:*:*:*
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
    vendor: s3cfg-config
    product: s3cfg-config
  tags: amazon,s3,exposure,config,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/.s3cfg"

    matchers-condition: and
    matchers:
      - type: word
        name: s3cfg-config
        cpe: cpe:2.3:a:s3cfg-config:s3cfg-config:*:*:*:*:*:*:*:*
        words:
          - "access_key"
          - "bucket_location"
          - "secret_key"
        condition: and

      - type: word
        name: s3cfg-config-2
        cpe: cpe:2.3:a:s3cfg-config:s3cfg-config:*:*:*:*:*:*:*:*
        part: header
        words:
          - "text/plain"

      - type: status
        status:
          - 200
