id: webpack-config

info:
  name: Webpack Configuration File - Detect
  author: ambassify,s4e-io
  severity: info
  description: Webpack configuration file was detected.
  reference:
    - https://webpack.js.org/configuration/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
    cpe: cpe:2.3:a:webpack.js:webpack:*:*:*:*:node.js:*:*:*
  metadata:
    max-request: 1
    shodan-query: html:"webpack.config.js"
    product: webpack
    vendor: webpack.js
  tags: config,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/webpack.config.js"

    matchers-condition: and
    matchers:
      - type: word
        name: webpack
        cpe: cpe:2.3:a:webpack.js:webpack:*:*:*:*:node.js:*:*:*
        words:
          - "module.exports"
          - "const"
        condition: or

      - type: word
        name: webpack-2
        cpe: cpe:2.3:a:webpack.js:webpack:*:*:*:*:node.js:*:*:*
        part: header
        words:
          - "application/javascript"
          - "text/javascript"
        condition: or

      - type: word
        name: webpack-3
        cpe: cpe:2.3:a:webpack.js:webpack:*:*:*:*:node.js:*:*:*
        part: body
        words:
          - "<html"
          - "<!doctype"
        case-insensitive: true
        negative: true

      - type: status
        status:
          - 200
