id: aspnet-launchsettings-exposure

info:
  name: ASP.NET Launch Settings - Exposure
  author: theamanrawat
  severity: medium
  classification:
    cpe: cpe:2.3:a:aspnet:aspnet:*:*:*:*:*:*:*:*
  description: |
    Detected exposed launchSettings.json files in ASP.NET Core applications. This file contains environment variables and launch configurations that may leak sensitive information.
  reference:
    - https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments
  metadata:
    vendor: aspnet
    product: aspnet
  tags: aspnet,config,exposure,json,dotnet

http:
  - method: GET
    path:
      - "{{BaseURL}}/Properties/launchSettings.json"
      - "{{BaseURL}}/launchSettings.json"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        name: aspnet
        cpe: cpe:2.3:a:aspnet:aspnet:*:*:*:*:*:*:*:*
        part: body
        words:
          - "profiles"
          - "iisSettings"
          - "commandName"
          - "launchBrowser"
        condition: and

      - type: word
        name: aspnet-2
        cpe: cpe:2.3:a:aspnet:aspnet:*:*:*:*:*:*:*:*
        part: header
        words:
          - "application/json"

      - type: status
        status:
          - 200
