id: gunicorn-config-file

info:
  name: Gunicorn Config File - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    Gunicorn Config file is exposed.
  classification:
    cpe: cpe:2.3:a:gunicorn:gunicorn:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"gunicorn.conf.py"
    vendor: gunicorn
    product: gunicorn
  tags: exposure,files,gunicorn,vuln

http:
  - method: GET
    path:
      - '{{BaseURL}}/gunicorn.conf.py'

    matchers-condition: and
    matchers:
      - type: word
        name: gunicorn
        cpe: cpe:2.3:a:gunicorn:gunicorn:*:*:*:*:*:*:*:*
        part: body
        words:
          - 'bind ='
          - 'workers ='
        condition: and
        case-insensitive: true

      - type: word
        name: gunicorn-2
        cpe: cpe:2.3:a:gunicorn:gunicorn:*:*:*:*:*:*:*:*
        part: content_type
        words:
          - 'text/x-python'
