id: lighttpd-config-file

info:
  name: Lighttpd Config File - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    Lighttpd Config file is exposed.
  classification:
    cpe: cpe:2.3:a:lighttpd:lighttpd:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"lighttpd.conf"
    vendor: lighttpd
    product: lighttpd
  tags: exposure,files,lighttpd,vuln

http:
  - method: GET
    path:
      - '{{BaseURL}}/lighttpd.conf'

    matchers-condition: and
    matchers:
      - type: word
        name: lighttpd
        cpe: cpe:2.3:a:lighttpd:lighttpd:*:*:*:*:*:*:*:*
        part: body
        words:
          - 'server.document-root ='
          - 'server.port ='
        condition: and
        case-insensitive: true

      - type: word
        name: lighttpd-2
        cpe: cpe:2.3:a:lighttpd:lighttpd:*:*:*:*:*:*:*:*
        part: content_type
        words:
          - 'application/octet-stream'
