id: pipeline-configuration

info:
  name: Pipeline Configuration Exposure
  author: DhiyaneshDK
  severity: info
  classification:
    cpe: cpe:2.3:a:jenkins:pipeline\\:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: jenkins
    product: pipeline\\
    shodan-query: html:"pipeline.yaml"
  tags: devops,exposure,cicd,files,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/pipeline.yaml"

    matchers-condition: and
    matchers:
      - type: word
        name: pipeline\\
        cpe: cpe:2.3:a:jenkins:pipeline\\:*:*:*:*:*:*:*:*
        words:
          - 'system:'
          - 'project_name:'
        condition: and

      - type: status
        status:
          - 200
