id: kube-api-nodes

info:
  name: Kube API Nodes
  author: sharath,ritikchaddha
  severity: info
  description: Scans for kube nodes
  classification:
    cpe: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: kubernetes
    product: kubernetes
  tags: tech,k8s,kubernetes,devops,kube,discovery

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/nodes"

    matchers-condition: or
    matchers:
      - type: word
        name: kubernetes
        cpe: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
        part: body
        words:
          - '"NodeList":'
          - '"items":'
        condition: and

      - type: word
        name: kubernetes-2
        cpe: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
        part: body
        words:
          - '"containerRuntimeVersion"'
          - '"kubeletVersion": "v'
        condition: and
