id: api-netlify

info:
  name: Netlify API Test
  author: dwisiswant0
  severity: info
  reference:
    - https://docs.netlify.com/api/get-started/
  classification:
    cpe: cpe:2.3:a:netlify:netlify:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: netlify
    product: netlify
  tags: token-spray,netlify

self-contained: true

http:
  - method: GET
    path:
      - "https://api.netlify.com/api/v1/sites"

    headers:
      Authorization: Bearer {{token}}
    matchers:
      - type: word
        name: netlify
        cpe: cpe:2.3:a:netlify:netlify:*:*:*:*:*:*:*:*
        part: body
        words:
          - '"id":'
          - '"premium":'
          - '"claimed":'
        condition: and
