id: api-appveyor

info:
  name: AppVeyor API Test
  author: dwisiswant0
  severity: info
  reference:
    - https://www.appveyor.com/docs/api/
  classification:
    cpe: cpe:2.3:a:appveyor:appveyor:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: appveyor
    product: appveyor
  tags: token-spray,appveyor

self-contained: true

http:
  - method: GET
    path:
      - "https://ci.appveyor.com/api/roles"

    headers:
      Content-Type: application/json
      Authorization: Bearer {{token}}
    matchers:
      - type: word
        name: appveyor
        cpe: cpe:2.3:a:appveyor:appveyor:*:*:*:*:*:*:*:*
        part: body
        words:
          - '"roleId":'
          - '"created":'
        condition: and
