id: wp-config-setup

info:
  name: WordPress Setup Configuration
  author: princechaddha
  severity: high
  description: Exposed Wordpress Setup Configuration.
  reference:
    - https://smaranchand.com.np/2020/04/misconfigured-wordpress-takeover-to-remote-code-execution/
  classification:
    cpe: cpe:2.3:a:wp-config:wp-config:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: wp-config
    product: wp-config
  tags: wordpress,setup,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-admin/setup-config.php?step=1"

    matchers-condition: and
    matchers:
      - type: word
        name: wp-config
        cpe: cpe:2.3:a:wp-config:wp-config:*:*:*:*:*:*:*:*
        words:
          - "Below you should enter your database connection details."

      - type: status
        status:
          - 200
