id: springboot-loggerconfig

info:
  name: Spring Boot LoggerConfig Actuator Panel - Detect
  author: DhiyaneshDK
  severity: info
  description: Spring Boot LoggerConfig Actuator panel was detected.
  reference:
    - https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
  classification:
    cpe: cpe:2.3:a:springboot:springboot:*:*:*:*:*:*:*:*
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: title:"Eureka"
    vendor: springboot
    product: springboot
  tags: misconfig,springboot,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/loggingConfig"
      - "{{BaseURL}}/actuator/loggingConfig"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        name: springboot
        cpe: cpe:2.3:a:springboot:springboot:*:*:*:*:*:*:*:*
        part: body
        words:
          - '["loggingConfig"]'
          - '"propertySources"'
        condition: and

      - type: word
        name: springboot-2
        cpe: cpe:2.3:a:springboot:springboot:*:*:*:*:*:*:*:*
        part: header
        words:
          - "application/json"
          - "application/vnd.spring-boot.actuator"
          - "application/vnd.spring-boot.actuator.v1+json"
        condition: or

      - type: status
        status:
          - 200
